### PR TITLE
fix sockjs version

### PR DESCRIPTION
**Pull request by 0x3A2B**

### CODE REVIEW

**Comment by breeswish** [comment]
Why pinning to a specific version?

**Comment by 0x3A2B** [comment]
> Why pinning to a specific version?

oj can’t work with 0.9.0,I tried 0.6.0 it works.

**Comment by twd2** [comment]
What is the latest workable version of sockjs?

**Comment by 0x3A2B** [comment]
> What is the latest workable version of sockjs?

it's 0.7.0 on my machine

**Comment by breeswish** [comment]
Hmm. I think the best solution should be make it work with latest version instead of pinning an old version.

**Comment by 0x3A2B** [comment]
> Hmm. I think the best solution should be make it work with latest version instead of pinning an old version.

Well...that is hard to me....I can't do that.

**Comment by twd2** [comment]
You can just try and pin at 0.7.0, and upgrading dependencies is a new issue #427 .

**Comment by iceb0y** [comment]
> You can just try and pin at 0.7.0, and upgrading dependencies is a new issue #427 .

so `sockjs>=0.6.0,<0.8.0` for now

**Comment by twd2** [comment]
> > You can just try and pin at 0.7.0, and upgrading dependencies is a new issue #427 .
> 
> so `sockjs>=0.6.0,<0.8.0` for now

@0x3A2B PTAL

**Comment by 0x3A2B** [comment]
> > > You can just try and pin at 0.7.0, and upgrading dependencies is a new issue #427 .
> > 
> > 
> > so `sockjs>=0.6.0,<0.8.0` for now
> 
> @0x3A2B PTAL

THX

**Comment by moesoha** [comment]
`sockjs>=0.6.0,<0.8.0` is not ok with current version as well.

There is 0.7.1 after 0.7.0, which is incompatible.

**Comment by twd2** [comment]
GG

**Comment by moesoha** [comment]
@twd2 

> GG

Check #432 plz

**Pull request merged**
