### PR TITLE
Fix #441

### LINKED ISSUE #441: Domain username alias causing server error
```
Dec 16 08:08:49 vj4wz001 vj4[47918] server.py E Error handling request
Traceback (most recent call last):
  File "/home/vj4/.local/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 390, in start
    resp = await self._request_handler(request)
  File "/home/vj4/.local/lib/python3.6/site-packages/aiohttp/web_app.py", line 366, in _handle
    resp = await handler(request)
  File "/home/vj4/git/vj4/vj4/handler/base.py", line 228, in __await__
    yield from super(Handler, self).__await__()
  File "/home/vj4/.local/lib/python3.6/site-packages/aiohttp/web_urldispatcher.py", line 740, in _iter
    resp = await method()
  File "/home/vj4/git/vj4/vj4/handler/user.py", line 225, in get
    ddocs=ddocs, dcount=dcount, vndict=vndict)
  File "/home/vj4/git/vj4/vj4/handler/base.py", line 255, in render
    self.response.text = self.render_html(template_name, **kwargs)
  File "/home/vj4/git/vj4/vj4/handler/base.py", line 204, in render_html
    return template.Environment().get_template(template_name).render(kwargs)
  File "/home/vj4/.local/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/vj4/.local/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/vj4/.local/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vj4/.local/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/vj4/git/vj4/vj4/ui/templates/user_detail.html", line 2, in top-level template code
    {% extends "layout/basic.html" %}
  File "/home/vj4/git/vj4/vj4/ui/templates/layout/basic.html", line 2, in top-level template code
    {% extends "layout/html5.html" %}
  File "/home/vj4/git/vj4/vj4/ui/templates/layout/html5.html", line 36, in top-level template code
    {% block body %}{% endblock %}
  File "/home/vj4/git/vj4/vj4/ui/templates/layout/basic.html", line 12, in block "body"
    {% block content %}{% endblock %}
  File "/home/vj4/git/vj4/vj4/ui/templates/user_detail.html", line 7, in block "content"
    <div class="profile-header user-profile-bg--{{ vj4.model.adaptor.setting.UserSetting(udoc).get_setting('background_img') }}">
  File "/home/vj4/git/vj4/vj4/model/adaptor/setting.py", line 78, in get_setting
    if self.has_priv(builtin.PRIV_USER_PROFILE) and key in self.domain_user:
AttributeError: 'UserSetting' object has no attribute 'domain_user'
```

### PR DESCRIPTION
**Pull request by moesoha**

### CODE REVIEW

**Comment by twd2** [comment]
CI is blocking...

**Comment by moesoha** [comment]
> CI is blocking...

https://www.traviscistatus.com/incidents/tmr79p73q6j8

**Comment by iceb0y** [comment]
Thanks. Server updated.

**Comment by iceb0y** [comment]
Seeing more errors. See #443.

**Pull request merged**
