### PR TITLE
Ignore rows that udoc doesn't exist

### PR DESCRIPTION
**Pull request by mikumikuchan**
Fix https://github.com/vijos/vj4/issues/365

### CODE REVIEW

**Comment by twd2** [comment]
Do not ignore, show a dummy user.

Closing

**Comment by breeswish** [comment]
Why do we need to show a dummy user even for deleted ones? Those are deleted users, which should not be visible anyway.

**Comment by ksyx** [comment]
This issue is well-solved in [This Page](https://vijos.org/p/1709), why not apply this solution to other places( such as contest scoreboard)?

**Comment by iceb0y** [comment]
I prefer to keep the row even when the user is not found.

**Pull request closed without merging**
