### PR TITLE
fix: regex matching of email address

### PR DESCRIPTION
**Pull request by tc-imba**
When matching emails with special characters before "@", the regex fails because it assume the last character is "\w", but it is not always the case.

```python3
import re
MAIL_RE = re.compile(r'\w+([-+.\w]+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*')
MAIL_RE_WRONG = re.compile(r'\w+([-+.]\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*')

bool(MAIL_RE.fullmatch('foo-.-@exmaple.com')) == True
bool(MAIL_RE_WRONG.fullmatch('foo-.-@exmaple.com')) == False
````

(This is the real case we met)

### CODE REVIEW

**Comment by iceb0y** [comment]
Changed to "[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+" from https://emailregex.com

**Comment by twd2** [comment]
I don't think `@a..` is an eligible hostname, but it is accepted by `@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+`.

???

**Comment by tc-imba** [comment]
I think `[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+` is too generous in matching...
The domain part @twd2 looks good.

Also according to https://en.wikipedia.org/wiki/Email_address#Syntax
The local part can be ```\.?[!#$%&'*+-/=?^_`{|}~\w]+(\.[!#$%&'*+-/=?^_`{|}~\w]+)*\.?```
if not considering the quotes (") and characters only available in quotes.
(I don't know anyone using these special characters but seems they are in the standard?)

**Comment by iceb0y** [comment]
Changed to [`[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-])+`](https://regex101.com/r/PwAJKv/1) to forbid `@a..` domain.

Note that we should avoid `\w` since it's related to python locale.

Feel free to give another negative example :)

**Comment by twd2** [comment]
`@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)+` is wrong. It accepts `@-.-`.

Ref: https://en.wikipedia.org/wiki/Email_address#Syntax

The domain name part of an email address has to conform to strict guidelines: it must match the requirements for a hostname, a list of dot-separated DNS labels, each label being limited to a length of 63 characters and consisting of:

uppercase and lowercase Latin letters A to Z and a to z;
digits 0 to 9, provided that top-level domain names are not all-numeric;
hyphen -, provided that it is not the first or last character.

**Comment by iceb0y** [comment]
We can compromise some correctness for simplicity here, as false positive here doesn't harm. If we want to validate against the full email address specification, then I think regular expression is not the right tool. Let's proceed with the current change?

**Comment by twd2** [comment]
Okay.

**Comment by iceb0y** [comment]
Server updated.

**Pull request merged**
