### PR TITLE
#420

### PR DESCRIPTION
**Pull request by masnn**

### CODE REVIEW

**Comment by masnn** [comment]
just tell user "we use regulex to search."
some advanced user may want this feature.

**Comment by moesoha** [comment]
Bad. Not all users understand "What is 'regular expression'". They just want to do a normal search as they do on Google/Baidu.

**Comment by masnn** [comment]
Not all users understand "What is 'markdown'". They just want to edit problems as they do on Microsoft Word.

**Comment by twd2** [comment]
Attackers can construct special regex to perform DoS attacks.

**Comment by masnn** [comment]
> Attackers can construct special regex to perform DoS attacks.

Please give an example.

**Comment by masnn** [comment]
?

**Comment by twd2** [comment]
https://www.google.com/search?q=regex+dos

**Comment by moesoha** [comment]
@twd2 user input is escaped, so ReDoS wont happen.

And I made a mistake before, exposing regex field to user WILL cause issues.

**Comment by masnn** [comment]
The regex have been already escaped.

**Comment by masnn** [comment]
Maybe we can support advanced search in the format like github.
e.g.: ac:>999 submit:<=3000

**Comment by twd2** [comment]
Okay, I see.

But, `title` and `content` are not indexed..

**Comment by twd2** [comment]
BTW, the original design is to use ElasticSearch (@breeswish )

**Pull request closed without merging**
