### PR TITLE
Fix SettingMixin for users not in current domain

### PR DESCRIPTION
**Pull request by moesoha**

### CODE REVIEW

**Comment by twd2** [comment]
@iceb0y PTAL

**Comment by iceb0y** [comment]
I would prefer to make `domain_user` always available.

Also `PRIV_USER_PROFILE` should be checked exactly once.

**Comment by twd2** [comment]
Note: these `dudoc`s come from 
https://github.com/vijos/vj4/blob/master/vj4/handler/discussion.py#L171
and
https://github.com/vijos/vj4/blob/master/vj4/handler/user.py#L188
.

**Comment by moesoha** [comment]
Only two classes inherited `SettingMixin`, `BaseHandler` and `UserSetting`. In `BaseHandler`, `self.domain_user` will be set to `{}` if it is `None`. So I do the same thing in `UserSetting`.

**Pull request merged**
