### PR TITLE
Correct default ip header in README

### PR DESCRIPTION
**Pull request by dianlujitao**
* Fix inconsistency with python side

### CODE REVIEW

**Comment by twd2** [comment]
Fix `README.md` please, the default value is changed to empty intentionally.

**Comment by breeswish** [comment]
In common scenarios, the server is served directly to the public network so that it's not secure to read IP address from headers by default, which can be forged.

**Comment by twd2** [comment]
This PR is to fix inconsistency. @breeswish

**Comment by dianlujitao** [comment]
Done

**Pull request merged**
